---
- hosts: nomad
  become: yes
  tasks:
  - name: Install rkt
    apt:
      deb: http://ftp.ch.debian.org/debian/pool/main/r/rkt/rkt_1.30.0+dfsg-7+b21_i386.deb

  - name: Install Consul
    include_role:
      name: brianshumate.consul
    vars:
      consul_architecture: "386"
      consul_bootstrap_expect: true
      consul_client_address: "0.0.0.0"
      consul_group_name: home
      consul_node_role: server

  - name: Install Nomad
    include_role:
      name: brianshumate.nomad
    vars:
      nomad_architecture: "386"
      nomad_group_name: home
      nomad_node_role: both
