---
- hosts: home
  become: yes
  tasks:
  - name: Install dependencies
    apt:
      name: python3-netaddr
      state: present

  - name: Install Consul
    include_role:
      name: brianshumate.consul
    vars:
      consul_bootstrap_expect: true
      consul_client_address: "0.0.0.0"
      consul_group_name: home

  - name: Install Nomad
    include_role:
      name: brianshumate.nomad
    vars:
      nomad_group_name: home
