name: "Build and Deploy"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Homelab
      url: "https://app.cachix.org/deploy/workspace/lab.thewagner.home/"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "extra-platforms = aarch64-linux"
      - name: Check
        run: nix flake check
      - name: Build
        run: nix build --print-build-logs .#cachix-deploy-spec
      - run: tree result
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: rpi-iso
      #     path: result/sd-image
      #     retention-days: 5